### ISSUE TITLE
Broken download link in README

### ISSUE THREAD

**Issue by catetrai** [TIO-IKIM/MOMO_Submission_Code#1]
Hi,

the link in the README for downloading the networks (https://cloud.uk-essen.de/d/340cc6654419476ab683/) returns a 404 error. Could you update it with a valid link?

Thank you for taking the effort to open-source this whole work! It's so bizarrely rare to find a paper in this field (AI in medical imaging) accompanied by usable code + models + test data. I hope you get recognition for it. And yes, the README *is* pretty good :D

Cheers,
Caterina

**Comment by FJonske** [comment]
Hey,

thanks for taking the time and creating an issue (and for flattering me). I have emailed you a new link (the old one having expired for some reason), and once I get back to work on Wednesday I will update the repo aswell.

**Comment by FJonske** [comment]
Finally got around to updating the link in the repo as well.
